FROM getmeili/meilisearch:v1.29


#    healthcheck:
#      test:
#        [
#          "CMD",
#          "wget",
#          "--no-verbose",
#          "--spider",
#          "http://127.0.0.1:7700/health",
#        ]
#      retries: 5
#      timeout: 10s
#      interval: 30s
#      start_period: 60s